Storage:
  # The interval in seconds to save all protection data. Default: 60
  Save-Interval: 60

Key-Item:
  # The material of the key item.
  # For a list of all available materials, see:
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
  Material: TRIPWIRE_HOOK

  # The name of the key item.
  # Color codes (ยง and &) can be used.
  Name: '&rKey'

  # The lore of the key item.
  # Every row represents a row in the lore.
  # Color codes (ยง and &) can be used.
  Lore:
    - ''
    - '&7&lRight-click a block'
    - '&7&lto lock it or to manage'
    - '&7&lthe existing access restrictions.'

  Crafting:
    # Each row represents a row inside the crafting field.
    # Every character used here, must be assigned a material,
    # otherwise it will represent an empty slot.
    Format:
      - 'XII'
      - 'XIX'
      - 'XTX'

    # For a list of all available materials, see:
    # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
    Ingredients:
      T: TRIPWIRE_HOOK
      I: IRON_INGOT

Protections:
  Container:
    - CHEST
    - TRAPPED_CHEST
    - FURNACE
    - DISPENSER
    - DROPPER
    - ANVIL
    - BEACON
    - BREWING_STAND
    - SHULKER_BOX
    - BLACK_SHULKER_BOX
    - BLUE_SHULKER_BOX
    - BROWN_SHULKER_BOX
    - CYAN_SHULKER_BOX
    - GRAY_SHULKER_BOX
    - GREEN_SHULKER_BOX
    - LIGHT_BLUE_SHULKER_BOX
    - LIGHT_GRAY_SHULKER_BOX
    - LIME_SHULKER_BOX
    - MAGENTA_SHULKER_BOX
    - ORANGE_SHULKER_BOX
    - PINK_SHULKER_BOX
    - PURPLE_SHULKER_BOX
    - RED_SHULKER_BOX
    - WHITE_SHULKER_BOX
    - YELLOW_SHULKER_BOX
    - LOOM
    - BARREL
    - SMOKER
    - BLAST_FURNACE
    - CARTOGRAPHY_TABLE
    - GRINDSTONE
    - STONECUTTER
    - ENCHANTMENT_TABLE
    - ENCHANTING_TABLE
  Interactable:
    - JUKEBOX
    - CAULDRON
    - STONE_BUTTON
    - WOOD_BUTTON
    - ACACIA_BUTTON
    - BIRCH_BUTTON
    - DARK_OAK_BUTTON
    - JUNGLE_BUTTON
    - OAK_BUTTON
    - SPRUCE_BUTTON
    - LEVER
    - ARMOR_STAND
  Door:
    - TRAP_DOOR
    - ACACIA_TRAPDOOR
    - BIRCH_TRAPDOOR
    - DARK_OAK_TRAPDOOR
    - IRON_TRAPDOOR
    - JUNGLE_TRAPDOOR
    - OAK_TRAPDOOR
    - SPRUCE_TRAPDOOR
    - WOODEN_DOOR
    - SPRUCE_DOOR
    - BIRCH_DOOR
    - JUNGLE_DOOR
    - ACACIA_DOOR
    - DARK_OAK_DOOR
    - DARK_OAK_DOOR
    - ACACIA_DOOR
    - BIRCH_DOOR
    - JUNGLE_DOOR
    - OAK_DOOR
    - SPRUCE_DOOR
    - FENCE_GATE
    - SPRUCE_FENCE_GATE
    - BIRCH_FENCE_GATE
    - JUNGLE_FENCE_GATE
    - DARK_OAK_FENCE_GATE
    - ACACIA_FENCE_GATE
    - OAK_FENCE_GATE

# Do not change this value!
Version: 1
