name: deinProtect
version: ${project.version}
authors: [leNic]
main: bz.dcr.deinprotect.DeinProtectPlugin
depend: [dcCore, SlimyGuis, BlocksHub]
api-version: 1.13

commands:
  deinprotect:
    usage: /<command> <key>
    description: deinProtect Befehl
    aliases: [dp, dprotect]
