name: deinProtect
version: ${project.version}
authors: [leNic]
main: bz.dcr.deinprotect.DeinProtectPlugin
depend: [dcCore, SlimyGuis, BlocksHub]

commands:
  deinprotect:
    usage: /<command> <key>
    description: deinProtect Befehl
    aliases: [dp, dprotect]